name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload plugin JARs
        uses: actions/upload-artifact@v4
        with:
          name: PitbullyPlugin-${{ github.sha }}
          path: |
            target/PitbullyPlugin-*.jar
            target/*-shaded.jar
          if-no-files-found: warn
