name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [21]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
        
    - name: Run unit tests
      run: mvn clean test -B -Dsurefire.failIfNoSpecifiedTests=false
      env:
        MAVEN_OPTS: "-Dfile.encoding=UTF-8"
        
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests (JDK ${{ matrix.java-version }})
        path: target/surefire-reports/*.xml
        reporter: java-junit
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-jdk${{ matrix.java-version }}
        path: |
          target/surefire-reports/
          
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build plugin
      run: mvn clean compile package -B -DskipTests
      
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v4
      with:
        name: PitbullyPlugin-jar
        path: target/PitbullyPlugin-*.jar
        retention-days: 30
        
    - name: Check plugin size
      run: |
        ls -lh target/PitbullyPlugin-*.jar
        echo "Plugin built successfully!"
