name: MockBukkit Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-with-mockbukkit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Run MockBukkit Integration Tests
      run: |
        echo "🚀 Running MockBukkit Integration Tests..."
        mvn clean test -Dtest=RealServerMigrationTest
        echo "✅ MockBukkit tests completed!"
    
    - name: Run All Tests (including MockBukkit)
      run: |
        echo "🧪 Running complete test suite..."
        mvn clean test
        echo "✅ All tests completed!"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: target/surefire-reports/
    
    - name: Test Report Summary
      if: always()
      run: |
        echo "## 📊 Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "MockBukkit Integration Tests demonstrate real Bukkit server testing!" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Real Location serialization/deserialization" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Actual Bukkit World objects in tests" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Production data migration verification" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ No more NullPointerExceptions from missing Bukkit server!" >> $GITHUB_STEP_SUMMARY
